#! /bin/bash -e

# print the Description of the given Changelist

function die(){
    echo $1
    exit -1
}

if [ $# -lt 1 ]
then
    die "usage: $0 CL-number"
fi




p4 changelist -o  $1|\
sed --quiet '/^Description:/,/^Files:/p'|tail -n +2|head -n +2

# '/WORD1/,/WORD2/p'
#awk '/^Description:/,/^Files:/'
# awk -grep Description:


#between ^Description: and ^Files:
