#! /bin/bash -eu



usage()
{
    cat >&2 <<EOF
Usage:    $0 [ -t {local-changelist} ] [-f] {shelved-changelist}

If given local-changelist, it will REVERT it and then Unshelve
  shelved-changelist into it.

-f forces unshelving.
When not given, a new pending CL is created, with a special description.
EOF

#    echo "usage: ${0##*/} [+-t CL ] [-f] [--] CL"
}


DESTINATION=
UNSHELVE_OPTS=""

while getopts :t:f OPT; do
    case $OPT in
	t|+t)
	    # to:
	    DESTINATION=$OPTARG
	    ;;
	f|+f)
	    # force
	    UNSHELVE_OPTS="-f"
	    ;;
	?)
	    echo "$0: wrong option $OPT"
	    usage
	    exit 2
    esac
done
shift $(( OPTIND - 1 ))
OPTIND=1




if [ $# -ne 1 ]
then
	usage;
	exit -1
fi

from=$1

if [ -z "$DESTINATION" ]
then
    DESTINATION=$(p4-create-pending-cl "unshelving $from")
    echo "created a new Pending CL $DESTINATION" >&2
else
    # fixme: This is confusion:
    # //... ?
    if p4 revert -c $DESTINATION ...
    then
	true;
    else
	echo ERROR
    fi
fi


# echo Now unshelving

if
    # echo p4 unshelve ${UNSHELVE_OPTS} -s $from -c $DESTINATION
    p4 unshelve ${UNSHELVE_OPTS} -s $from -c $DESTINATION |\
        colortail -k ${P4SHARE:-~/tomtom/}/p4-unshelve.color -
then
    true;
else
    echo ERROR
    exit 1;
fi;

